@echo off
echo [Shark Canvas] Setting up MSVC environment...
call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
echo [Shark Canvas] Starting Tauri dev...
npm run tauri dev
