@echo off
echo [Maestri-X] Setting up MSVC environment...
call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
echo [Maestri-X] Starting Tauri dev...
npm run tauri dev
